[package]
name = "raw-guile"
version = "0.1.0"
edition = "2024"
authors = ["MinkieYume <minkieyume@yumieko.com>"]
description = "Safe bindings to GNU Guile."
repository = "https://github.com/minkieyume/ngrs"
license = "MIT OR Apache-2.0"

[build-dependencies]
bindgen = "0.70"
pkg-config = "0.3"